spring:
  application:
    name: restaurant-kitchen
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/kitchen
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  rabbitmq:
    host: localhost
    port: 5672
    username: amit
    password: amit

server:
  port: 8004

management:
  endpoints:
    web:
      exposure:
        include: "*"
      expose: "*"

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
